
(require 'eaf)
(require 'eaf-browser)

(setq eaf-browser-keybinding
      '(("." . nil)
        ("C--" . "zoom_out")
        ("C-+" . "zoom_in")
        ("C-0" . "zoom_reset")
        ("C-f" . "search_text_forward")
        ("C-r" . "search_text_backward")
        ("h" . "insert_or_scroll_up")
        ("t" . "insert_or_scroll_down")
        ("d" . "insert_or_scroll_left")
        ("n" . "insert_or_scroll_right")
        ;; ("SPC" . "insert_or_scroll_up_page")
        ("C-p" . "scroll_up_page")
        ("M-p" . "scroll_down_page")
        ("C-v" . "yank_text")
        ("C-x" . "kill_text")
        ("M-z" . "switch_to_input_mode")
        ("C-z" . "undo_action")
        ("C-Z" . "redo_action")
        ("C-j" . "copy_text")
        ("r" . "insert_or_history_forward")
        ("l" . "insert_or_history_backward")
        ("<" . "insert_or_scroll_to_begin")
        (">" . "insert_or_scroll_to_bottom")
        ("C-n" . "new_blank_page")
        ("i" . "insert_or_focus_input")
        ("-" . "insert_or_zoom_out")
        ("+" . "insert_or_zoom_in")
        ("0" . "insert_or_zoom_reset")
        ("G" . "insert_or_open_browser")
        ("<escape>" . "eaf-browser-send-esc-or-exit-fullscreen")))

(setq eaf-browser-search-engines
      '(("google" . "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%s")
        ("duckduckgo" . "https://duckduckgo.com/?q=%s")
        ("bing" . "https://bing.com/search?q=%s")
        ("youtube" . "https://www.youtube.com/results?search_query=%s")))

(defun youtube ()
  (interactive)
  (eaf-search-it (read-string "[EAF/browser] Search (YouTube): ") "youtube"))
