#!/bin/sh

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

set -o emacs

# Aliases
alias ls='exa'
#alias l='exa --icons --long --all --no-permissions --no-filesize --no-user --no-time'
alias l='exa --icons --all --oneline'
alias ll='exa --icons --long --all --header --git'
alias c='clear'
alias cl='c; l'
alias f='pfetch && df -h'
alias pf='pfetch'
alias nf='neofetch'
alias e='emacsclient -nw'
alias settings='xfce4-settings-manager'
alias bat='bat --theme base16'
alias n='cd $HOME/.nix-configuration'
alias fm='pcmanfm -n'
alias i='sxiv -g 1200x1600 -r -t *'
alias directory='if [ "$PWD" == "$HOME" ]; then echo \'~'; else; basename "$PWD"; fi'

HISTFILE="$HOME/.ksh_history"
HISTSIZE=500

# Prompt
ksh_prompt() {
    black=$'\E[0;30m'
    red=$'\E[0;31m'
    green=$'\E[0;32m'
    yellow=$'\E[0;33m'
    blue=$'\E[0;34m'
    magenta=$'\E[0;35m'
    cyan=$'\E[0;36m'
    white=$'\E[0;37m'
    bold=$'\E[1m'
    uline=$'\E[4m'
    reset=$'\E[0m'

    # Finding the git branch
    #git rev-parse --abbrev-ref HEAD
    #git status 2>/dev/null | grep 'On branch' | sed 's/On branch / => /'
    #git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'

    # How many files were modified git
    #git status -s | sed -n '$='
    #if [ "git status -s | sed -n '$='" == "" ]; then echo "modified"; fi

    # Aesthetics
    #╭╴
    #╰─>
    #╰─❯
    # ╭─ ~/src  master 

    export PS1="╭╴${cyan} ${reset}${yellow}${bold}\$(directory)${reset} ${green}${uline}\$(git rev-parse --abbrev-ref HEAD 2>/dev/null)${reset}
╰─λ "
    #export PS1="${cyan} ${reset}${yellow}\$(directory)${reset} ${green}${uline}\$(git rev-parse --abbrev-ref HEAD 2>/dev/null)${reset}
    #$ "
    #export PS1="${green}\$(directory) $ ${reset}"
    #export PS1=$'\E[31m$(logname)@$(hostname -s):$PWD $ \E[0m'
    #export PS1=$'\E[31m$(logname)@$(hostname -s):$PWD $ \E[0m'
}

ksh_prompt unset ksh_prompt
