{ config, lib, pkgs, ... }:
with lib;

let
  cfg = config.services.cory.plank;
in {
  options.services.cory.plank = {
    enable = mkEnableOption "Enable plank";
  };

  config = mkIf cfg.enable {
    programs.dconf.enable = true;

    home-manager.users.cory.dconf = {
      enable = true;
      settings = {
        "net/launchpad/plank/docks/dock1" = {
          alignment = "center";
          auto-pinning = true;
          current-workspace-only = false;
          dock-items = [
            "rofi.dockitem"
            "pcmanfm-qt.dockitem"
            "urxvtc.dockitem"
            "firefox.dockitem"
            "emacsclient.dockitem"
            "discord.dockitem"
            "audacious.dockitem"
            "photogimp.dockitem"
            "steam.dockitem"
          ];
          hide-delay = 0;
          hide-mode = "intelligent";
          icon-size = 54;
          items-alignment = "center";
          lock-items = false;
          monitor = "";
          offset = 0;
          pinned-only = false;
          position = "right";
          pressure-reveal = false;
          show-dock-item = false;
          theme = config.theme.name;
          tooltips-enabled = true;
          unhide-delay = 0;
          zoom-enabled = true;
          zoom-percent = 150;
        };
      };
    };

    home-manager.users.cory.home.file.".local/share/plank/themes/${config.theme.name}/dock.theme".text = ''
      #This file auto-generated by Plank.
      #2016-03-12T14:53:46+0000

      [PlankTheme]
      #The roundness of the top corners.
      TopRoundness=8
      #The roundness of the bottom corners.
      BottomRoundness=0
      #The thickness (in pixels) of lines drawn.
      LineWidth=2
      #The color (RGBA) of the outer stroke.
      OuterStrokeColor=232;;232;;232;;255
      #The starting color (RGBA) of the fill gradient.
      FillStartColor=232;;232;;232;;255
      #The ending color (RGBA) of the fill gradient.
      FillEndColor=255;;255;;255;;255
      #The color (RGBA) of the inner stroke.
      InnerStrokeColor=20;;20;;4;;255

      [PlankDockTheme]
      #The padding on the left/right dock edges, in tenths of a percent of IconSize.
      HorizPadding=0
      #The padding on the top dock edge, in tenths of a percent of IconSize.
      TopPadding=-11
      #The padding on the bottom dock edge, in tenths of a percent of IconSize.
      BottomPadding=2.5
      #The padding between items on the dock, in tenths of a percent of IconSize.
      ItemPadding=2.5
      #The size of item indicators, in tenths of a percent of IconSize.
      IndicatorSize=5
      #The size of the icon-shadow behind every item, in tenths of a percent of IconSize.
      IconShadowSize=1
      #The height (in percent of IconSize) to bounce an icon when the application sets urgent.
      UrgentBounceHeight=1.6666666666666667
      #The height (in percent of IconSize) to bounce an icon when launching an application.
      LaunchBounceHeight=0.625
      #The opacity value (0 to 1) to fade the dock to when hiding it.
      FadeOpacity=1
      #The amount of time (in ms) for click animations.
      ClickTime=300
      #The amount of time (in ms) to bounce an urgent icon.
      UrgentBounceTime=600
      #The amount of time (in ms) to bounce an icon when launching an application.
      LaunchBounceTime=600
      #The amount of time (in ms) for active window indicator animations.
      ActiveTime=300
      #The amount of time (in ms) to slide icons into/out of the dock.
      SlideTime=300
      #The time (in ms) to fade the dock in/out on a hide (if FadeOpacity is < 1).
      FadeTime=250
      #The time (in ms) to slide the dock in/out on a hide (if FadeOpacity is 1).
      HideTime=250
      #The size of the urgent glow (shown when dock is hidden), in tenths of a percent of IconSize.
      GlowSize=30
      #The total time (in ms) to show the hidden-dock urgent glow.
      GlowTime=10000
      #The time (in ms) of each pulse of the hidden-dock urgent glow.
      GlowPulseTime=2000
      #The hue-shift (-180 to 180) of the urgent indicator color.
      UrgentHueShift=150
      #The time (in ms) to move an item to its new position or its addition/removal to/from the dock.
      ItemMoveTime=450
      #Whether background and icons will unhide/hide with different speeds. The top-border of both will leave/hit the screen-edge at the same time.
      CascadeHide=true
      #The color (RGBA) of the badge displaying urgent count
      BadgeColor=0;;0;;0;;0
    '';

    environment = {
      systemPackages = with pkgs; [
        plank
      ];
    };
  };
}
