#!/bin/sh

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# Neovim config
alias vim='nvim'
export EDITOR='nvim'
alias ls='exa'
alias l='exa -lah'
alias c='clear'

# Prompt
bash_prompt() {
    black="\e[0;30m"
    red="\e[0;31m"
    green="\e[0;32m"
    yellow="\e[0;33m"
    blue="\e[0;34m"
    magenta="\e[0;35m"
    cyan="\e[0;36m"
    white="\e[0;37m"
    bold="\e[1m"
    uline="\e[4m"
    reset="\e[0m"
    
    #git rev-parse --abbrev-ref HEAD
    #git status 2>/dev/null | grep 'On branch' | sed 's/On branch / => /'
    
    export PS1="${cyan}${bold} ${reset}${yellow}${bold}\W${reset} ${green}${uline}\$(git rev-parse --abbrev-ref HEAD 2>/dev/null)${reset}\n╰─❯ "
}

bash_prompt
unset bash_prompt
