{ config }:
with config.theme.color;
''
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>uuid</key>
    <string>D8D5E82E-3D5B-46B5-B38E-8C841C21347D</string>
    <key>name</key>
    <string>${config.theme.name}</string>
    <key>author</key>
    <string>cory</string>
    <key>semanticClass</key>
    <string>theme.${if config.theme.darkTheme then "dark" else "light"}.plain</string>
    <key>settings</key>
    <array>
      <dict>
	<key>settings</key>
	<dict>
	  <key>background</key>
	  <string>${background}</string>
	  <key>caret</key>
	  <string>${foreground}</string>
	  <key>foreground</key>
	  <string>${foreground}</string>
	  <key>lineHighlight</key>
	  <string>${background-alt1}</string>
	  <key>invisibles</key>
	  <string>${background-alt4}</string>
	  <key>selection</key>
	  <string>${background-alt4}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Comment</string>
	<key>scope</key>
	<string>comment, string.quoted.docstring</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${color4}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>String</string>
	<key>scope</key>
	<string>string</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${color2}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Number</string>
	<key>scope</key>
	<string>constant.numeric</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Built-in constant</string>
	<key>scope</key>
	<string>constant.language</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>User-defined constant</string>
	<key>scope</key>
	<string>constant.character, constant.other</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Variable</string>
	<key>scope</key>
	<string>variable</string>
	<key>settings</key>
	<dict>
	  <key>fontStyle</key>
	  <string></string>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Keyword</string>
	<key>scope</key>
	<string>keyword</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Storage</string>
	<key>scope</key>
	<string>storage</string>
	<key>settings</key>
	<dict>
	  <key>fontStyle</key>
	  <string></string>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Storage type</string>
	<key>scope</key>
	<string>storage.type</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Class name</string>
	<key>scope</key>
	<string>entity.name.class, entity.name.type, meta.class.python, storage.type.scala</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${color3}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Parent class name</string>
	<key>scope</key>
	<string>meta.class.inheritance.python</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Function name</string>
	<key>scope</key>
	<string>entity.name.function</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${color3}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Function argument</string>
	<key>scope</key>
	<string>variable.parameter</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Tag name</string>
	<key>scope</key>
	<string>entity.name.tag</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Tag attribute</string>
	<key>scope</key>
	<string>entity.other.attribute-name</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Library function</string>
	<key>scope</key>
	<string>support.function</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Library constant</string>
	<key>scope</key>
	<string>support.constant</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Library class&#x2f;type</string>
	<key>scope</key>
	<string>support.type, support.class</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${foreground}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Library variable</string>
	<key>scope</key>
	<string>support.other.variable</string>
	<key>settings</key>
	<dict>
	  <key>fontStyle</key>
	  <string></string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Invalid</string>
	<key>scope</key>
	<string>invalid</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${color1}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Invalid deprecated</string>
	<key>scope</key>
	<string>invalid.deprecated</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${color5}</string>
	</dict>
      </dict>
      <dict>
	<key>name</key>
	<string>Whitespace</string>
	<key>scope</key>
	<string>punctuation.whitespace</string>
	<key>settings</key>
	<dict>
	  <key>foreground</key>
	  <string>${color0}</string>
	</dict>
      </dict>
    </array>
  </dict>
</plist>
''
