#!/bin/bash

dir=$1
if [ "$dir" == "" ]
then
    exit 1
fi

xdgmenumaker -i -f fvwm -s 32 \
    | grep -v -G "Title$" \
    | sed s#'\+ "\(.*\)%.*\(48x48\|128x128\|256x256\|512x512\|pixmaps\|racket\|airshipper\).*"'#'+ "\1"'# \
    > $dir/XDGMenu

cat <<END
Read $dir/XDGMenu
END
