#!/bin/bash

dir=$1
if [ "$dir" == "" ]
then
    exit 1
fi

xdgmenumaker -f fvwm -i -s 32 --max-icon-size \
    | grep -v -G "Title$" \
    | sed '3i + "Search" Exec exec rofi -show drun -config /home/cory/rofi.rasi' \
    > $dir/XDGMenu

cat <<END
Read $dir/XDGMenu
END
