#+title:Xmomacs

This rice/setup is designed to be a merge between xmonad and exwm.

Essentially it is xmonad but you use it like emacs.
The window management is xmonad but the user interaction with the wm is like emacs.
This makes for a uniform interaction between the system and the emacs program.

Xmonad but you use it like exwm.
The frontend user experience and user interation is the exact
same as you would use exwm, except with xmonad features and an xmonad backend.



Xmonad is my bootloader into emacs
I do everything through emacs, xmonad is just there to manage X applications
that aren't managed through emacs.
Xmonad immediate keybindings are keybindings that are guarenteed to not be
overrided. They are only for window management and other tasks that need
immediate keybindings.
Personal keybindings and non-window-management specific stuff will be accessed
through emacs-like prefix bindings.

Emacs is controlled through SPACE.
XMonad is controlled through Super + SPACE.

Another goal is to keep keybinds as simple as possible and have as little
keybinds as possible for simplicity.
And the keybinds that do exist must make sense with what they do.

Another goal is to try to keep hands on the home-row as much as possible.
