#!/bin/sh

layout=$(setxkbmap -query | grep layout | awk 'END{print $2}')

if [[ "$layout" == "us_minimak" ]]
then
  setxkbmap "ru_phonetic_minimak"
elif [[ "$layout" == "ru_phonetic_minimak" ]]
then
  setxkbmap "us_minimak"
elif [[ "$layout" == "us_qwerty" ]]
then
  setxkbmap "ru_phonetic_qwerty"
elif [[ "$layout" == "ru_phonetic_qwerty" ]]
then
  setxkbmap "us_qwerty"
else
  setxkbmap "us_minimak"
fi
